### ISSUE TITLE
Handler Class doesn't exist

### ISSUE THREAD

**Issue by IAmJulianAcosta** [echo-it/laravel-jsonapi#1]
Hi, I'm trying to implement the example but I'm stuck here:

```
if (class_exists($handlerClass)) {
```

I'm always getting: 

```
{"errors":[{"code":404,"title":"Entity not found"}]}
```

Am I missing something?

**Comment by egeriis** [comment]
Hi Julian,

Did you create a handler class for your endpoint in the API namespace?

In the example we use a UsersHandler class in the API namespace for the /users endpoint.

**Comment by IAmJulianAcosta** [comment]
Hi

I created the class, and did exactly what is in the instructions, but with no luck

**Comment by egeriis** [comment]
The "Entity not found" error will be returned if the handler class does not exist. Are you sure you've put your handler class file in the right place?

**Comment by IAmJulianAcosta** [comment]
Could you show me what is "the right place"?

Thank you

**Comment by egeriis** [comment]
According to your autoloading schema. If you're using the default Laravel 4 setup, you can place an `API\UsersHandler` in a folder named `api` in either `commands`, `controllers` or `models`.

In the projects I've used this module, I've placed the handlers in `models/api` since they are basically a link between models and the endpoint.

**Comment by IAmJulianAcosta** [comment]
Thank you for your support, I was able to fix it, It would be nice if you can update the docs with this, so newbies like me could know about this :)

**Comment by egeriis** [comment]
Sure, that's no problem. Thank you for the feedback!
